# -*- coding: utf-8 -*-
"""Speach-To-Text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RNgKIvuvvE4B1bLrk7oAq6NyeomL8fZa
"""

!pip install -U openai-whisper
!pip install transformers
!pip install librosa

import whisper

model = whisper.load_model("large")

import librosa
def preprocess_audio(file_path):
    audio, sr = librosa.load(file_path, sr=16000)  # Resample to 16kHz
    return audio

# Transcribe the audio file
def transcribe_audio(file_path):
    result = model.transcribe(file_path)
    return result["text"]

import os
import csv
# Transcribe all .wav files in a folder and save results to a CSV
def transcribe_folder_and_save_to_csv(folder_path, csv_path):
    # Create/open CSV file
    with open(csv_path, mode='w', newline='', encoding='utf-8') as csv_file:
        writer = csv.writer(csv_file)
        writer.writerow(["File Name", "Transcription"])  # Write CSV header

        # Loop through all files in the folder
        for file_name in os.listdir(folder_path):
            if file_name.endswith(".wav"):  # Check for .wav files
                file_path = os.path.join(folder_path, file_name)

                # Transcribe audio file
                transcription = transcribe_audio(file_path)

                # Write the file name and transcription to the CSV
                writer.writerow([file_name, transcription])

                # Print the transcription (optional)
                print(f"File: {file_name}")
                print(f"Transcription: {transcription}\n")

# Example usage:

folder_path = "/content/drive/MyDrive/tai"  # Path to folder with .wav files
csv_output_path = "/content/transcriptions.csv"  # Output CSV file path

# Transcribe files and save results to CSV
transcribe_folder_and_save_to_csv(folder_path, csv_output_path)

print(f"Transcriptions saved to {csv_output_path}")